### PR TITLE
docs: LSDV-5343: Docs for visibleWhen; remove FF_DEV_1372

### PR DESCRIPTION
**Pull request by hlomzik**
Document `visibleWhen` and connected `when*` properties to highlight their depencies on each other. Even if some nuances will be improved and validated in the future, these nuances right now will help users a lot to understand problems with configs.

Basically, `visibleWhen` is required parameter, can refer to choices or regions, both selected or unselected:
- region-selected, can specify tag and label value, both are optional
- choice-selected, can specify tag, and with tag specified can specify choice value
- no-region-selected, can't specify anything else
- choice-unselected, can specify tag, and with tag specified can specify choice value
Can be applied to `View` and `Choices` tags.

Also small FF_DEV_1372 was removed because it's enabled everywhere. And documentation for `choice-unselected` option by this FF was added to docs.

### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Frontend

#### What feature flags were used to cover this change?
`ff_front_dev_1372_visible_when_choice_unselected_11022022_short` removed

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Visibility, Taxonomy, Choices

### CODE REVIEW

**Review by yyassi-heartex — COMMENTED** [review]
looks good to me, just missing some unit tests - aside from that its ready for approval

**Review by yyassi-heartex — APPROVED** [review]

**Comment by hlomzik** [comment]
> just missing some unit tests
we have e2e tests already, unit tests will come in next PRs

**Pull request merged**
